apiVersion: v1
kind: Pod
metadata:
  name: demo-writer
  labels:
    app: demo-writer
spec:
  restartPolicy: Never
  containers:
    - name: writer
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          set -eux
          echo "hello $(date -Iseconds)" > /data/hello.txt
          ls -la /data
          sync
          sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo-pvc
