apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nas-system
resources:
  - 00-secrets/smb-user-alice.yaml
  - 10-pool/zpool.yaml
  - 20-dataset/zdataset-home.yaml
  - 20-dataset/zdataset-timemachine.yaml
  - 30-smb/smbshare-home.yaml
  - 30-smb/smbshare-timemachine.yaml
  - 40-snapshots/zsnapshotschedule-home.yaml
  - 50-restore/zsnapshotrestore-clone.yaml
