apiVersion: v1
kind: Service
metadata:
  name: nas-api
  namespace: nas-system
spec:
  type: NodePort
  selector:
    app: nas-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
