apiVersion: nas.io/v1alpha1
kind: ZDataset
metadata:
  name: tank-home
  namespace: nas-system
spec:
  nodeName: worker-1
  datasetName: tank/home
  preset: smb
  properties:
    acltype: nfsv4
    aclmode: restricted
    casesensitivity: insensitive
    atime: "on"
    compression: lz4
    mountpoint: /mnt/tank/home
    snapdir: visible
