apiVersion: nas.io/v1alpha1
kind: ZDataset
metadata:
  name: tank-nfs
  namespace: nas-system
spec:
  nodeName: worker-1
  datasetName: tank/nfs
  preset: generic
  properties:
    acltype: posix
    casesensitivity: sensitive
    compression: "lz4"
    mountpoint: /mnt/tank/nfs
    snapdir: visible
