apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-operator-to-node-agent
  namespace: nas-system
spec:
  podSelector:
    matchLabels:
      app: nas-node-agent
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              nas.io/component: operator
      ports:
        - protocol: TCP
          port: 9808
