apiVersion: v1
kind: ServiceAccount
metadata:
  name: nas-node-agent
  namespace: nas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nas-node-agent
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nas-node-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nas-node-agent
subjects:
  - kind: ServiceAccount
    name: nas-node-agent
    namespace: nas-system
