apiVersion: v1
kind: Service
metadata:
  name: nas-node-agent
  namespace: nas-system
spec:
  selector:
    app: nas-node-agent
  ports:
    - name: http
      port: 9808
      targetPort: 9808
  type: ClusterIP
