apiVersion: nas.io/v1alpha1
kind: ZSnapshotRestore
metadata:
  name: home-restore-clone
  namespace: nas-system
spec:
  nodeName: worker-1
  sourceSnapshot: AUTO
  mode: clone
  targetDataset: tank/home-restore-test
