apiVersion: nas.io/v1alpha1
kind: NASUser
metadata:
  name: alice
  namespace: nas-system
spec:
  username: alice
  directoryRef: local
  uid: 10001
  primaryGroup: users
  passwordSecretRef:
    name: smb-user-alice
