apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timemachine-pvc
  namespace: nas-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Keep this small for lab/demo environments; resize as needed.
      storage: 5Gi
  storageClassName: nas-zfspv
