apiVersion: nas.io/v1alpha1
kind: NASDirectory
metadata:
  name: ad
  namespace: nas-system
spec:
  type: activeDirectory
  servers:
    - ldaps://192.168.1.8:636
  baseDN: DC=nas,DC=local
  realm: NAS.LOCAL
  workgroup: NAS
  bind:
    username: Administrator
    secretRef:
      name: ad-bind
  tls:
    verify: true
    caBundleSecretRef:
      name: ad-ca
  idMapping:
    strategy: rfc2307
    uidAttribute: uidNumber
    gidAttribute: gidNumber
