apiVersion: v1
kind: Pod
metadata:
  name: demo-reader
  labels:
    app: demo-reader
spec:
  restartPolicy: Never
  containers:
    - name: reader
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          set -eux
          cat /data/hello.txt
          ls -la /data
          sleep 3600
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo-restore-pvc
