apiVersion: nas.io/v1alpha1
kind: ZSnapshotRestore
metadata:
  name: demo-restore
spec:
  mode: csi
  sourceVolumeSnapshot: demo-snap
  targetPVC: demo-restore-pvc
  storageClassName: nas-zfspv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
